name: Test Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Success Step
        run: echo "Project Running"

      - name: Intentional Failure
        run: exit 1